# git one
name: CI Pipeline

on:
  push:
    branches:
      - dev_cal_app
  pull_request:
    branches:
      - dev_cal_app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      # You can test your matrix by printing the current Python version
      - name: Run unit tests
        run: pytest -vv

